### ISSUE TITLE
About the contents in "Readme"

### ISSUE THREAD

**Issue by wang422003** [xguo7/PCVAE#1]
Hi, I really appreciate the work and code. But I just found something which confused me. 

According to the code, the model is based on Pytorch. But in "Readme", it is said that it is based on TensorFlow. Would you please kindly let me know which one is correct? Or there is supposed to be another release based on TensorFlow?

Many thanks in advance.

**Comment by xguo7** [comment]
Sorry for the late reply. It is based on pytorch and we will change it soon.
